kind: pipeline
type: docker
name: RTX

clone:
  depth: 50

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: registry.teledhil.eu/rtx
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: registry.teledhil.eu
    dockerfile: Dockerfile
    build_args:
    - APT_PROXY: teledhil.eu
    cache_from: registry.teledhil.eu/rtx
- name: build
  image: registry.teledhil.eu/rtx
  commands:
  - git submodule update --recursive --remote
  - ./build.sh

image_pull_secrets:
- docker_login_json
